name: manage-azure-policy-b8ae0c3a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Require_a_tag_and_its_value_on_resource_groups_8ce3da23-7156-49e4-b145-24f95f9dcb46/**'
#      - 'policies/Inherit_a_tag_from_the_subscription_if_missing_40df99da-1232-49b1-a39a-6da8d878f469/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_Web_Applications_5744710e-cc2f-4ee8-8809-3b11e89f4bc9/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_API_App_358c20a6-3f9e-4f0e-97ff-c6ce485e2aac/**'
#      - 'policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**'
#      - 'policies/Secure_transfer_to_storage_accounts_should_be_enabled_404c3081-a854-4457-ae30-26a93ef643f9/**'
#      - 'policies/Storage_accounts_should_prevent_shared_key_access_8c6a50c6-9ffd-4ae7-986f-5fa6111f9a54/**'
#      - 'policies/Storage_account_containing_the_container_with_activity_logs_must_be_encrypted_with_BYOK_fbb99e8e-e444-4da0-9ff1-75c92f5a85b2/**'
#      - 'policies/Virtual_machines_should_be_migrated_to_new_Azure_Resource_Manager_resources_1d84d5fb-01f6-4d12-ba4f-4a26081d403d/**'
#      - 'policies/An_Azure_Active_Directory_administrator_should_be_provisioned_for_SQL_servers_1f314764-cb73-4fc9-b863-8eca98ac36e9/**'
#      - 'policies/External_accounts_with_owner_permissions_should_be_removed_from_your_subscription_f8456c1c-aa66-4dfb-861a-25d127b775c9/**'
#      - 'policies/External_accounts_with_read_permissions_should_be_removed_from_your_subscription_5f76cf89-fbf2-47fd-a3f4-b891fa780b60/**'
#      - 'policies/External_accounts_with_write_permissions_should_be_removed_from_your_subscription_5c607a2e-c700-4744-8254-d77e7c9eb5e4/**'
#      - 'policies/MFA_should_be_enabled_accounts_with_write_permissions_on_your_subscription_9297c21d-2ed6-4474-b48f-163f75654ce3/**'
#      - 'policies/MFA_should_be_enabled_on_accounts_with_owner_permissions_on_your_subscription_aa633080-8b72-40c4-a2d7-d00c03e80bed/**'
#      - 'policies/Custom_subscription_owner_roles_should_not_exist_10ee2ea2-fb4d-45b8-a7e9-a2e770044cd9/**'
#      - 'policies/Subscriptions_should_have_a_contact_email_address_for_security_issues_4f4f78b8-e367-4b10-a341-d9a4ad5cf1c7/**'
#      - 'policies/Email_notification_for_high_severity_alerts_should_be_enabled_6e2593d9-add6-4083-9c9b-4b7d2188c899/**'
#      - 'policies/Email_notification_to_subscription_owner_for_high_severity_alerts_should_be_enabled_0b15565f-aa9e-48ba-8619-45960f2c314d/**'
#      - 'policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**'
#      - .github/workflows/manage-azure-policy-b8ae0c3a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b8ae0c3a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Require_a_tag_and_its_value_on_resource_groups_8ce3da23-7156-49e4-b145-24f95f9dcb46/**
          policies/Inherit_a_tag_from_the_subscription_if_missing_40df99da-1232-49b1-a39a-6da8d878f469/**
          policies/CORS_should_not_allow_every_resource_to_access_your_Web_Applications_5744710e-cc2f-4ee8-8809-3b11e89f4bc9/**
          policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**
          policies/CORS_should_not_allow_every_resource_to_access_your_API_App_358c20a6-3f9e-4f0e-97ff-c6ce485e2aac/**
          policies/Storage_account_keys_should_not_be_expired_044985bb-afe1-42cd-8a36-9d5d42424537/**
          policies/Secure_transfer_to_storage_accounts_should_be_enabled_404c3081-a854-4457-ae30-26a93ef643f9/**
          policies/Storage_accounts_should_prevent_shared_key_access_8c6a50c6-9ffd-4ae7-986f-5fa6111f9a54/**
          policies/Storage_account_containing_the_container_with_activity_logs_must_be_encrypted_with_BYOK_fbb99e8e-e444-4da0-9ff1-75c92f5a85b2/**
          policies/Virtual_machines_should_be_migrated_to_new_Azure_Resource_Manager_resources_1d84d5fb-01f6-4d12-ba4f-4a26081d403d/**
          policies/An_Azure_Active_Directory_administrator_should_be_provisioned_for_SQL_servers_1f314764-cb73-4fc9-b863-8eca98ac36e9/**
          policies/External_accounts_with_owner_permissions_should_be_removed_from_your_subscription_f8456c1c-aa66-4dfb-861a-25d127b775c9/**
          policies/External_accounts_with_read_permissions_should_be_removed_from_your_subscription_5f76cf89-fbf2-47fd-a3f4-b891fa780b60/**
          policies/External_accounts_with_write_permissions_should_be_removed_from_your_subscription_5c607a2e-c700-4744-8254-d77e7c9eb5e4/**
          policies/MFA_should_be_enabled_accounts_with_write_permissions_on_your_subscription_9297c21d-2ed6-4474-b48f-163f75654ce3/**
          policies/MFA_should_be_enabled_on_accounts_with_owner_permissions_on_your_subscription_aa633080-8b72-40c4-a2d7-d00c03e80bed/**
          policies/Custom_subscription_owner_roles_should_not_exist_10ee2ea2-fb4d-45b8-a7e9-a2e770044cd9/**
          policies/Subscriptions_should_have_a_contact_email_address_for_security_issues_4f4f78b8-e367-4b10-a341-d9a4ad5cf1c7/**
          policies/Email_notification_for_high_severity_alerts_should_be_enabled_6e2593d9-add6-4083-9c9b-4b7d2188c899/**
          policies/Email_notification_to_subscription_owner_for_high_severity_alerts_should_be_enabled_0b15565f-aa9e-48ba-8619-45960f2c314d/**
          policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**
